project:
  type: book
  output-dir: docs

book:
  title: "Dairy *versus* Transhumance"
  author: "Andreas Angourakis"
  date: today
  date-format: DD MMMM, YYYY
  search: true
  repo-url: https://github.com/Andros-Spica/dairy-vs-transhumance/
  sharing: [twitter, facebook]
  site-url: https://andros-spica.github.io/dairy-vs-transhumance/
  page-navigation: true
  chapters:
    - index.qmd
    - introduction.qmd
    - demonstration.qmd
    - sensitivity-analysis.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

